# Generated by Django 2.2.6 on 2019-11-29 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('leader', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=150)),
                ('rank', models.CharField(choices=[('ADMIN', 'admin'), ('MEMBER', 'member')], default='MEMBER', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=10)),
                ('password', models.CharField(max_length=251)),
                ('credits', models.IntegerField(default=100)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='UserProfile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline', models.DateField(auto_created=True)),
                ('date_created', models.DateField(auto_created=True)),
                ('title', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=20)),
                ('project_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.ProjectGroup')),
            ],
        ),
        migrations.AddField(
            model_name='projectgroup',
            name='user_profile',
            field=models.ManyToManyField(to='authentication.UserProfile'),
        ),
    ]
