# Generated by Django 2.2.6 on 2019-11-29 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectgroup',
            name='rank',
        ),
    ]
