# Generated by Django 2.2.6 on 2019-11-29 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_projectgroup_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectgroup',
            name='rank',
            field=models.CharField(choices=[('ADMIN', 'admin'), ('MEMBER', 'member')], default='MEMBER', max_length=10),
        ),
    ]
